---
- name: Terraform Output
  shell: terraform output -json > output.json
  args:
    chdir: "{{ terraform_path }}/02-server"
  delegate_to: localhost
  environment:
    AWS_REGION: "{{ aws_region }}"
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"

- name: Get NLB DNS Name
  vars:
    terraform_outputs: "{{ lookup('file', '{{ terraform_path }}/02-server/output.json') }}"
    nlb_dns_name: "{{ terraform_outputs.nlb_dns_name.value }}"
  debug:
    var: nlb_dns_name
